import { useState } from "react";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";

const schema = z.object({ name: z.string().trim().min(1, "Name is required").max(100), email: z.string().trim().email("Please enter a valid email").max(255), phone: z.string().trim().min(1, "Phone is required").max(40), company: z.string().trim().max(150), message: z.string().trim().min(1, "Message is required").max(2000), enquiry: z.string().max(100) });
export function ContactForm({ workWithUs = false }: { workWithUs?: boolean }) {
 const { toast } = useToast(); const [sending, setSending] = useState(false); const [data, setData] = useState({ name:"", email:"", phone:"", company:"", message:"", enquiry: workWithUs ? "I want to work with Oworks" : "Marketing assistance" });
 const onChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setData((current) => ({ ...current, [e.target.name]: e.target.value }));
 const onSubmit = async (e: React.FormEvent) => { e.preventDefault(); const result = schema.safeParse(data); if (!result.success) { toast({ title: "Please check your details", description: result.error.issues[0]?.message ?? "Invalid form data.", variant:"destructive" }); return; } setSending(true); await new Promise((resolve) => setTimeout(resolve, 500)); setSending(false); toast({ title:"Message received", description:"Thank you for contacting Oworks. We’ll be in touch soon." }); setData({ name:"", email:"", phone:"", company:"", message:"", enquiry: workWithUs ? "I want to work with Oworks" : "Marketing assistance" }); };
 return <form onSubmit={onSubmit} className="space-y-8"><div><label className="eyebrow block mb-3" htmlFor="name">Name *</label><input className="input-editorial" id="name" name="name" value={data.name} onChange={onChange} maxLength={100} required /></div><div><label className="eyebrow block mb-3" htmlFor="email">Email *</label><input className="input-editorial" type="email" id="email" name="email" value={data.email} onChange={onChange} maxLength={255} required /></div><div><label className="eyebrow block mb-3" htmlFor="phone">Phone *</label><input className="input-editorial" type="tel" id="phone" name="phone" value={data.phone} onChange={onChange} maxLength={40} required /></div><div><label className="eyebrow block mb-3" htmlFor="company">Company</label><input className="input-editorial" id="company" name="company" value={data.company} onChange={onChange} maxLength={150} /></div><div><label className="eyebrow block mb-3" htmlFor="enquiry">I’m contacting Oworks about</label><select className="input-editorial bg-transparent" id="enquiry" name="enquiry" value={data.enquiry} onChange={onChange}><option>Marketing assistance</option><option>I want to work with Oworks</option></select></div><div><label className="eyebrow block mb-3" htmlFor="message">Message *</label><textarea className="input-editorial resize-none" id="message" name="message" value={data.message} onChange={onChange} maxLength={2000} rows={6} required /></div><Button type="submit" disabled={sending}>{sending ? "Sending..." : "Connect with Us"}</Button></form>;
}
